using System.Collections.Generic;
using Terraria.ID;

namespace WorldLevel.Models
{
    public enum NPCRarity
    {
        Normal = 0,
        Hostile = 1,
        Special = 2,
        SuperRare = 3,
    }

    public class NPCRarityConfig
    {
        public Dictionary<NPCRarity, int> RequiredKillsMin { get; set; } = new()
        {
            { NPCRarity.Normal, 80 },
            { NPCRarity.Hostile, 30 },
            { NPCRarity.Special, 15 },
            { NPCRarity.SuperRare, 3 },
        };

        public Dictionary<NPCRarity, int> RequiredKillsMax { get; set; } = new()
        {
            { NPCRarity.Normal, 160 },
            { NPCRarity.Hostile, 80 },
            { NPCRarity.Special, 30 },
            { NPCRarity.SuperRare, 5 },
        };

        public Dictionary<NPCRarity, int> RequiredKills { get; set; } =
            new()
            {
                { NPCRarity.Normal, 120 },
                { NPCRarity.Hostile, 55 },
                { NPCRarity.Special, 22 },
                { NPCRarity.SuperRare, 4 },
            };

        public Dictionary<NPCRarity, double> XPMultipliers { get; set; } =
            new()
            {
                { NPCRarity.Normal, 2.5 }, // Base XP
                { NPCRarity.Hostile, 8.5 }, // 2x XP
                { NPCRarity.Special, 23.5 }, // 3.5x XP
                { NPCRarity.SuperRare, 44.8 },
            };

        public HashSet<int> HostileNPCs { get; set; } =
            new()
            {
                1,
                3,
                2,
                173,
                6,
                49,
                51,
                150,
                35,
                164,
                165,
                59,
                60,
                61,
                10,
                11,
                12,
                117,
                118,
                119,
                47,
                57,
                168,
                81,
                83,
                183,
                34,
                32,
                62,
                133,
                190,
                191,
                192,
                193,
                194,
                24,
                26,
                27,
                28,
                29,
                378,
                58,
                250,
                257,
                69,
                77,
                475,
                39,
                40,
                41,
                46,
                101,
                217,
                94,
                494,
                467,
                7,
                8,
                9,
                95,
                96,
                97,
                468,
                71,
                84,
                581,
                224,
                226,
                162,
                259,
                122,
                93,
                152,
                111,
                55,
                48,
                174,
                42,
                147,
                268,
                137,
                236,
                -10,
                388,
                386,
                383,
                392,
                387,
                16,
                258,
                252,
                148,
                213,
                215,
                214,
                491,
                492,
                75,
                262,
                140,
                244,
                156,
                172,
                269,
                270,
                271,
                541,
                542,
                5,
                65,
                21,
                110,
                293,
                291,
                302,
                187,
                56,
                145,
                185,
                143,
                204,
                221,
                405,
                406,
                407,
                408,
                411,
                409,
                410,
                403,
                402,
                404,
                292,
                53,
                141,
                546,
                44,
                167,
                86,
                158,
                161,
                223,
                320,
                321,
                331,
                319,
                332,
                338,
                254,
                23,
                555,
                552,
                566,
                561,
            };

        public HashSet<int> SpecialNPCs { get; set; } =
            new()
            {
                179,
                14,
                13,
                586,
                198,
                631,
                243,
                290,
                618,
                544,
                621,
                87,
                104,
                172,
                45,
                85,
                475,
                476,
                629,
                196,
                477,
                216,
                205,
                251,
                109,
                156,
                153,
                154,
                454,
                520,
                385,
                463,
                466,
                469,
                159,
                479,
                467,
                315,
                329,
                330,
                326,
                343,
                351,
                348,
                347,
                350,
                341,
                412,
                507,
                517,
                493,
                422,
                570,
                553,
                562,
                559,
                574,
                568,
                572,
                73,
                82,
                513,
            };

        public HashSet<int> SuperRareNPCs { get; set; } =
            new()
            {
                NPCID.EyeofCthulhu,
                NPCID.KingSlime,
                NPCID.EaterofWorldsTail,
                NPCID.BrainofCthulhu,
                NPCID.QueenBee,
                NPCID.Deerclops,
                NPCID.SkeletronHead,
                NPCID.WallofFlesh,
                NPCID.QueenSlimeBoss,
                NPCID.TheDestroyer,
                NPCID.SkeletronPrime,
                NPCID.Spazmatism,
                NPCID.Retinazer,
                NPCID.Plantera,
                NPCID.Golem,
                NPCID.DukeFishron,
                NPCID.CultistBoss,
                NPCID.HallowBoss,
                NPCID.BigMimicCrimson,
                NPCID.BigMimicCorruption,
                NPCID.Gnome,
                NPCID.GoblinSummoner,
                NPCID.SandSlime,
                NPCID.SpikedIceSlime,
                NPCID.VoodooDemon,
                NPCID.CursedHammer,
                NPCID.Shark,
                NPCID.DevourerHead,
                99,
            };

        public double GetXPMultiplier(int npcId)
        {
            if (SpecialNPCs.Contains(npcId))
                return XPMultipliers[NPCRarity.Special];
            if (HostileNPCs.Contains(npcId))
                return XPMultipliers[NPCRarity.Hostile];
            if (SuperRareNPCs.Contains(npcId))
                return XPMultipliers[NPCRarity.SuperRare];
            return XPMultipliers[NPCRarity.Normal];
        }
    }
}